version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "coverage_development"
    ports:
      - "5432:5432/tcp"
    restart: always
  web:
    build: .
    command: "pnpm run start:dev"
    depends_on:
      - db
    ports:
      - "3000:3000/tcp"
    restart: on-failure
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"