version: "3"

services:
  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "coverage_test"
    ports:
      - "5434:5432/tcp"
    restart: always