version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "coverage"
    ports:
      - "5432:5432/tcp"
    restart: always